import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";

import "./globals.css";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"], // customize weights as needed
});

export const metadata: Metadata = {
  title: "Cabinet Racines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={instrumentSans.className}>
      <body
        className={`${instrumentSans.className} ${instrumentSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
